### ISSUE TITLE
一个关于配合 Typora 图片生成功能的小建议

### ISSUE THREAD

**Issue by aturret** [soryu-ryouji/novel-tex-theme#4]
给 body 加一点 margin 会方便用 Typora 自带的功能生成图片。比如简单地改成这样：

```css
body {
  padding: 0 !important;
  margin: 24px 30px 24px 30px !important;
}
```

有些时候想用图片导出功能生成类似锤子便签之类的东西（效果非常好！）。Typora 默认的图片生成生成功能是用 body 的 padding 和 margin 去做图的，可以在设置里改图片宽度和字体大小。如果图片一点边距都没有的话会有点奇怪。

我不是专业搞前端设计的。我猜你 body 的 padding 和 margin 设置为0是为了让版式一致，在意的是编辑器上显示的 margin 也就是 `var(--set-margin)` 。这样可能是有些不优雅，我也不太懂怎么搞比较好哈哈。反正我是先随便加了点基于像素的 margin 把图片渲染这个问题解决了。
