### ISSUE TITLE
请问如何把四周边框去掉？

### ISSUE THREAD

**Issue by liu-evan** [soryu-ryouji/novel-tex-theme#6]
请问如何把四周边框去掉？

**Comment by soryu-ryouji** [comment]
您可以在所用的主题文件中，加入代码 `--border-color: var(--bg-color)`

这里我以 `novel-tex-f-l.css` 文件举例。

```css
@charset "UTF-8";
@import "./novel-tex/basic/include.css";
@import "./novel-tex/light/basic-light-config.css";

:root {
  --active-file-bg-color: rgb(192, 192, 192);
  --active-file-text-color: var(--text-color);

  --item-hover-bg-color: var(--active-file-bg-color);
  --item-hover-text-color: var(--active-file-text-color);

  /* 新增代码 */
  --border-color: var(--bg-color)
}
```

希望这能够帮助到您。
